### ISSUE TITLE
Failing to Extract Text on Lambda

### ISSUE THREAD

**Issue by slarrain** [skylander86/lambda-text-extractor#4]
Hi, I've just deployed the new version of your code, but I'm getting errors. In particular, when I try to run the example given on the Readme:
```sh
aws lambda invoke --function-name textractor_simple --payload '{"document_uri": "https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf", "temp_uri_prefix": "s3://text-extractor/", "text_uri": "s3://text-extractor/tracemonkey.txt"}' -
```
I get a:
```sh
{
    "StatusCode": 200
}
```
And no Errors on the lambda, but when I go see the extracted text file, it has 0 bytes, and Cloudwatch says this:
```sh
[ERROR] 2017-11-09T20:32:36.918Z 1e9cea26-c58d-11e7-9503-b7e3017ab9c2 Subprocess ['/var/task/bin/pdftotext', '-layout', '-nopgbrk', '-eol', 'unix', '/tmp/tmp8xi8qzza.pdf', '/tmp/tmpim1oc76s.txt'] returned 127:
Traceback (most recent call last):
File "/var/task/utils.py", line 8, in get_subprocess_output
output = subprocess.check_output(cmdline, **kwargs)
File "/var/lang/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/var/lang/lib/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/var/task/bin/pdftotext', '-layout', '-nopgbrk', '-eol', 'unix', '/tmp/tmp8xi8qzza.pdf', '/tmp/tmpim1oc76s.txt']' returned non-zero exit status 127.
```

And I'm a little puzzled. I believe the `pdftotext` binary should be in the `bin/` directory of the function. Maybe the libraries are having a problem? Is it working for you?

Thanks!

**Comment by ghost** [comment]
I'm having this exact same issue @slarrain did you get this figured out?

**Comment by skylander86** [comment]
Ah, I just fixed this. This is kinda a dumb bug. The Python .gitignore file includes `lib`, which meant that the `lib` folder with soft links to all the necessary `.so` libraries for all the executables were not committed to the repository. I just added those links back and merged to master. It should work now (see pull request #5).

Thanks for raising the issue!
