### ISSUE TITLE
Source Bucket Lambda Trigger

### ISSUE THREAD

**Issue by ghost** [skylander86/lambda-text-extractor#6]
Currently the way this is setup is through a manual invoke.

What would be the best steps to use a source bucket and a destination bucket?

**Comment by skylander86** [comment]
Sorry for the late reply.

You could set up the source S3 bucket to send a notification and trigger the lambda. But you would need to update the lambda code to parse the notification event message and set the variables accordingly. That should not be too complicated, you can find the event message schema [here](https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-s3-put).
