### ISSUE TITLE
Received error when trying to parse .jpg file. 

### ISSUE THREAD

**Issue by stkr89** [skylander86/lambda-text-extractor#7]
Following is the error response:

`{"errorMessage": "local variable 'textractor_results' referenced before assignment", 
"errorType": "UnboundLocalError", 
"stackTrace": [["/var/task/main.py", 128, "handle", 
"payload['results']['textractor'] = textractor_results"]]}`

**Comment by skylander86** [comment]
I think I fixed this issue. Try again and let me know? Thanks!

**Comment by stkr89** [comment]
Works fine now. Thanks
